application: head2head-hrishi
version: 1
runtime: python
api_version: 1

handlers:

- url: /stylesheets
  static_dir: stylesheets
  
- url: /img
  static_dir: img

- url: /static
  static_dir: static

- url: /.*
  script: asklogin.py


  
